### ISSUE TITLE
outline and proposal info available

### ISSUE THREAD

**Issue by kparrish92** [kparrish92/dissertation_parrish#1]
@jvcasillas 

Hello! 
An outline is available now under docs > outline.pdf 

My general plan for experiments is here: docs > proposal > slides > proposal_slides.Rmd

Please let me know what you think!

**Comment by kparrish92** [comment]
@jvcasillas reminder per our meeting

**Comment by jvcasillas** [comment]
Thanks for the reminder. Didn't forget, just haven't got to it yet.

**Comment by jvcasillas** [comment]
Outline looks fine. You might even consider a production-perception chapter, perhaps only looking at the vowels, but I don't think that it is necessary. Give it some thought and if it seems like you'll have something to say given the data you intend to collect you can throw that in too.
