### ISSUE TITLE
First 2 sections of the proposal are ready for feedback!

### ISSUE THREAD

**Issue by kparrish92** [kparrish92/dissertation_parrish#2]
Hi! 

I wanted to let you know that I've finished two sections of my intro and lit review for the proposal. I wanted to send them as early as possible. I broke the lit review into several R markdowns by topic. The first few are the introduction and a section where I introduce and L3 models and discuss their predictions and evidence. 

These can be found here: 
**Intro:** [docs/proposal/sections/01_intro.Rmd](https://github.com/kparrish92/dissertation_parrish/blob/main/docs/proposal/sections/01_intro.Rmd)
**Lit review section:** [dissertation_parrish/docs/proposal/sections/02_lit_review.Rmd](https://github.com/kparrish92/dissertation_parrish/blob/main/docs/proposal/sections/02_lit_review.Rmd)
**The present study** [dissertation_parrish/docs/proposal/sections/03_present_study.Rmd](https://github.com/kparrish92/dissertation_parrish/blob/main/docs/proposal/sections/03_present_study.Rmd)

Thanks! I'll keep you updated as I continue to finish subsections.

**Comment by kparrish92** [comment]
@jvcasillas - I am finally done with a first draft of the proposal! I updated the links above. I ended up with 3 sections - an intro, lit review, and "the present study". It ended up being around 45ish pages before references, so I hope I didn't miss anything major. 

What date do you think I can send to the committee (that I'll be sending them a draft)? We had said before Winter break, which I suppose is until 12/23 (end of the exam period).

**Comment by jvcasillas** [comment]
Awesome! Congrats. Let's shoot for this sunday. I'll look over it and barring any major problems (unlikely) you can send it off sunday evening.

**Comment by jvcasillas** [comment]
All done. PR is ready for review https://github.com/kparrish92/dissertation_parrish/pull/3

It might be a good idea to address some of the comments over the next day or so rather than sending it out tonight.
